Update Audinate Dante Virtual Soundcard pre and post install scripts
Updates the pre and post install scripts with the vendors new versions, and comments out the parts that generate a message to allow for silent installs.

diff --git a/Audinate Dante Virtual Soundcard/Reference Scripts Audinate Dante Virtual Soundcard/Fixed Scripts/postinstall b/Audinate Dante Virtual Soundcard/Reference Scripts Audinate Dante Virtual Soundcard/Fixed Scripts/postinstall
--- a/Audinate Dante Virtual Soundcard/Reference Scripts Audinate Dante Virtual Soundcard/Fixed Scripts/postinstall
+++ b/Audinate Dante Virtual Soundcard/Reference Scripts Audinate Dante Virtual Soundcard/Fixed Scripts/postinstall
@@ -10,31 +10,32 @@ INSTALL_LOGFILE="/Library/Logs/Audinate/DanteVirtualSoundcard/dvs_install.log"
 
 # Log System Integrity Protection status
 echo "*** System Integrity Protection ***" > $INSTALL_LOGFILE
-csrutil status >> $INSTALL_LOGFILE
+csrutil status >> $INSTALL_LOGFILE 2>&1
 
 # Log the contents of /Library/Audio/Plug-Ins/HAL/
 echo "\n*** Contents of $PLUGINS_HAL_PATH ***" >> $INSTALL_LOGFILE
-ls -al $PLUGINS_HAL_PATH >> $INSTALL_LOGFILE
+ls -al $PLUGINS_HAL_PATH >> $INSTALL_LOGFILE 2>&1
 
 if [ ! -d "$DVS_DRIVER_PATH" ] ||
-    [ ! -d "$DVS_LIBRARY_PATH" ] ||
-    [ ! -d "$DVS_GUI_PATH" ]; then
+	[ ! -d "$DVS_LIBRARY_PATH" ] ||
+	[ ! -d "$DVS_GUI_PATH" ]; then
 
-    # Comment out warning dialog
-    #osascript <<EOF
-    #   display dialog ("Failed to update the DVS audio driver. Please uninstall DVS first and then try installing DVS again.") with title "Install Dante Virtual Soundcard" with icon caution buttons {"OK"} default button 1
-    #EOF
+	echo "\n*** Failed to install the DVS audio driver or the GUI application ***" >> $INSTALL_LOGFILE
+	echo "\n*** Contents of $DVS_DRIVER_PATH ***" >> $INSTALL_LOGFILE
+	ls -al "$DVS_DRIVER_PATH"/* >> $INSTALL_LOGFILE 2>&1
+	ls -al "$DVS_DRIVER_PATH"/*/* >> $INSTALL_LOGFILE 2>&1
+	echo "\n*** Contents of $DVS_LIBRARY_PATH ***" >> $INSTALL_LOGFILE
+	ls -al "$DVS_LIBRARY_PATH"/* >> $INSTALL_LOGFILE 2>&1
+	echo "\n*** Contents of $DVS_GUI_PATH ***" >> $INSTALL_LOGFILE
+	ls -al "$DVS_GUI_PATH"/* >> $INSTALL_LOGFILE 2>&1
 
-    echo "\n*** Failed to install the DVS audio driver or the GUI application ***" >> $INSTALL_LOGFILE
-    echo "\n*** Contents of $DVS_DRIVER_PATH ***" >> $INSTALL_LOGFILE
-    ls -al "$DVS_DRIVER_PATH"/* >> $INSTALL_LOGFILE
-    ls -al "$DVS_DRIVER_PATH"/*/* >> $INSTALL_LOGFILE
-    echo "\n*** Contents of $DVS_LIBRARY_PATH ***" >> $INSTALL_LOGFILE
-    ls -al "$DVS_LIBRARY_PATH"/* >> $INSTALL_LOGFILE
-    echo "\n*** Contents of $DVS_GUI_PATH ***" >> $INSTALL_LOGFILE
-    ls -al "$DVS_GUI_PATH"/* >> $INSTALL_LOGFILE
+	# Comment out warning dialog to enable silent installation
+	# Show a warning dialog during installation if it fails to update the DVS audio driver
+	#display_alert "'messageText' 'Dante Virtual Soundcard installation failed' 'informativeText' 'Failed to install the DVS application or audio driver. Please uninstall DVS first and then try installing again.' 'alertStyle' 2 'icon' 'dvs-3.icns'"
 
-    exit 1
+	#delete_silent_install_file
+
+	exit 1
 fi
 
 OLD_COREAUDIOD_PID=$(pgrep coreaudiod)
@@ -45,46 +46,46 @@ sudo kill -9 $OLD_COREAUDIOD_PID
 count=0
 while :
 do
-    sleep 1
-    NEW_COREAUDIOD_PID=$(pgrep coreaudiod)
-    if [ "$NEW_COREAUDIOD_PID" != "$OLD_COREAUDIOD_PID" ]; then
-        break
-    fi
-    count=$((count+1))
-    if [[ $count -eq 10 ]]; then
-        echo "\n*** Failed to restart coreaudiod ***" >> $INSTALL_LOGFILE
-        break
-    fi
+	sleep 1
+	NEW_COREAUDIOD_PID=$(pgrep coreaudiod)
+	if [ "$NEW_COREAUDIOD_PID" != "$OLD_COREAUDIOD_PID" ]; then
+		break
+	fi
+	count=$((count+1))
+	if [[ $count -eq 10 ]]; then
+		echo "\n*** Failed to restart coreaudiod ***" >> $INSTALL_LOGFILE
+		break
+	fi
 done
 
 # Make sure the DVS Audio Plug-In Driver is running
 count=0
 while :
 do
-    sleep 1
-    DVS_AUDIO_PLUGIN_PID=$(pgrep ".*DvsAudioPlugIn.*")
-    if [ "$DVS_AUDIO_PLUGIN_PID" != "" ]; then
-        echo "\n*** DVS Audio Plug-In driver is running with PID: $DVS_AUDIO_PLUGIN_PID ***" >> $INSTALL_LOGFILE
-        break
-    fi
-    count=$((count+1))
-    if [[ $count -eq 10 ]]; then
-        echo "\n*** DVS Audio Plug-In Driver is not running ***" >> $INSTALL_LOGFILE
-        echo "\n*** Contents of $DVS_DRIVER_PATH ***" >> $INSTALL_LOGFILE
-        ls -al "$DVS_DRIVER_PATH"/* >> $INSTALL_LOGFILE
-        ls -al "$DVS_DRIVER_PATH"/*/* >> $INSTALL_LOGFILE
-        echo "\n*** Disk usage of $DVS_DRIVER_PATH ***" >> $INSTALL_LOGFILE
-        du -h "$DVS_DRIVER_PATH" >> $INSTALL_LOGFILE
-        break
-    fi
+	sleep 1
+	DVS_AUDIO_PLUGIN_PID=$(pgrep ".*DvsAudioPlugIn.*")
+	if [ "$DVS_AUDIO_PLUGIN_PID" != "" ]; then
+		echo "\n*** DVS Audio Plug-In driver is running with PID: $DVS_AUDIO_PLUGIN_PID ***" >> $INSTALL_LOGFILE
+		break
+	fi
+	count=$((count+1))
+	if [[ $count -eq 10 ]]; then
+		echo "\n*** DVS Audio Plug-In Driver is not running ***" >> $INSTALL_LOGFILE
+		echo "\n*** Contents of $DVS_DRIVER_PATH ***" >> $INSTALL_LOGFILE
+		ls -al "$DVS_DRIVER_PATH"/* >> $INSTALL_LOGFILE 2>&1
+		ls -al "$DVS_DRIVER_PATH"/*/* >> $INSTALL_LOGFILE 2>&1
+		echo "\n*** Disk usage of $DVS_DRIVER_PATH ***" >> $INSTALL_LOGFILE
+		du -h "$DVS_DRIVER_PATH" >> $INSTALL_LOGFILE 2>&1
+		break
+	fi
 done
 
 # Load manager
 launchctl load -w /Library/LaunchDaemons/com.audinate.dante.DanteVirtualSoundcard.plist > /dev/null 2>&1
 
-# Comment out restart notification dialog
-#osascript <<EOF
-#    display dialog "In order to complete the Dante Virtual Soundcard installation process, you will be required to restart your Mac." with title "Install Dante Virtual Soundcard" with icon caution buttons {"Continue"} default button "Continue"
-#EOF
+# Comment out restart notification dialog to enable silent installation
+#display_alert '"messageText" "Restart your Mac" "informativeText" "To complete the Dante Virtual Soundcard installation process, please restart your Mac." "alertStyle" 1 "icon" "dvs-3.icns"'
+
+#delete_silent_install_file
 
 exit 0
